# ==========================================
# Configuração SonarQube Scanner
# ==========================================
sonar.projectKey=ci-cd-sec-devsecops
sonar.projectName=DevSecOps Secure Development (CI/CD)
sonar.projectVersion=1.0.0

# Caminhos de código fonte e testes
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/coverage/**,**/*.spec.js

# Linguagens
sonar.language=js
sonar.sourceEncoding=UTF-8

# Qualidade de Código e Security Standards
sonar.qualitygate.wait=true
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=javascript:S100
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*
